## 테스트에서 쓸 값들 미리 지정
@username = user2345
@adminUsername = admin1234

@password1 = Abcdef12345!
@password2 = asdgfA123@42
@password3 = Ewwqas@12341
@password4 = dqwmmdsi@rt15
@password5 = test2T@#%
@password6 = 123kfuiAsd@$%

@nickname1 = first_name
@nickname2 = second_name

@updateNickname = update_test

@email = user123@email.com
@adminEmail = admin123@email.com

@updateEmail = update123@email.com

@userId = 1

@postId = 1

@categoryId = 1

@categoryTopic = 백엔드

@admincode = WkdWMlpXNTBaWElnYzNWd1pYSWdZV1J0YVc0Z1kyOWtaUT09

# 일반권한인 유저 테스트입니다.

### 일반 유저 회원 가입
POST http://localhost:8080/auth/sign-up
Content-Type: application/json

{
  "username":"{{username}}",
  "password":"{{password1}}",
  "nickname":"{{nickname1}}",
  "email":"{{email}}"
}


### 어드민 유저 회원가입
POST http://localhost:8080/auth/sign-up
Content-Type: application/json

{
  "username":"{{adminUsername}}",
  "password":"{{password1}}",
  "nickname":"{{nickname2}}",
  "email":"{{adminEmail}}",
  "adminStatus": true,
  "adminCode": "{{admincode}}"
}


### 일반 유저 로그인 (로그인 요청시 억세스토큰, 리플레시토큰 자동 저장 후 다른곳에서 가져다 쓸수 있습니다)
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username":"{{username}}",
  "password":"{{password1}}"
}

> {%
  client.global.set("Authorization", response.headers.valueOf("Authorization"));
  client.global.set("X-Refresh-Token", response.headers.valueOf("X-Refresh-Token"));
%}


### 어드민 유저 로그인 (로그인 요청시 억세스토큰, 리플레시토큰 자동 저장 후 다른곳에서 가져다 쓸수 있습니다)
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username":"{{adminUsername}}",
  "password":"{{password1}}"
}

> {%
  client.global.set("Authorization", response.headers.valueOf("Authorization"));
  client.global.set("X-Refresh-Token", response.headers.valueOf("X-Refresh-Token"));
%}


### 리플레시 토큰으로 억세스토큰 재발행
POST http://localhost:8080/auth/refresh
X-Refresh-Token:{{X-Refresh-Token}}

> {%
  client.global.set("Authorization", response.headers.valueOf("Authorization"));
  client.global.set("X-Refresh-Token", response.headers.valueOf("X-Refresh-Token"));
%}


### 유저 로그아웃
POST http://localhost:8080/auth/logout
Authorization:{{Authorization}}


### 유저 탈퇴
DELETE http://localhost:8080/auth/withdraw
Authorization:{{Authorization}}


### 유저 프로필 조회
GET http://localhost:8080/users/{{userId}}
Authorization: {{Authorization}}


### 유저 프로필 수정
PUT http://localhost:8080/users/{{userId}}
Authorization: {{Authorization}}
Content-Type: application/json

{
  "nickname": "{{updateNickname}}",
  "email": "{{updateEmail}}"
}


### 유저 프로필 수정 (원본으로)
PUT http://localhost:8080/users/{{userId}}
Authorization: {{Authorization}}
Content-Type: application/json

{
  "nickname": "{{nickname1}}",
  "email": "{{email}}"
}


### 유저 비밀번호 변경 1
PUT http://localhost:8080/users/{{userId}}/change-password
Authorization: {{Authorization}}
Content-Type: application/json

{
  "currentPassword": "{{password1}}",
  "newPassword": "{{password2}}"
}

### 유저 비밀번호 변경 2
PUT http://localhost:8080/users/{{userId}}/change-password
Authorization: {{Authorization}}
Content-Type: application/json

{
  "currentPassword": "{{password2}}",
  "newPassword": "{{password3}}"
}


### 유저 비밀번호 변경 3
PUT http://localhost:8080/users/{{userId}}/change-password
Authorization: {{Authorization}}
Content-Type: application/json

{
  "currentPassword": "{{password3}}",
  "newPassword": "{{password4}}"
}


### 유저 비밀번호 변경 4
PUT http://localhost:8080/users/{{userId}}/change-password
Authorization: {{Authorization}}
Content-Type: application/json

{
  "currentPassword": "{{password4}}",
  "newPassword": "{{password1}}"
}


### 카테고리 추가
POST http://localhost:8080/categories
Authorization: {{Authorization}}
Content-Type: application/json

{
  "topic": "{{categoryTopic}}"
}


### 카테고리 조회
GET http://localhost:8080/categories
Authorization: {{Authorization}}


### 카테고리 수정
PUT http://localhost:8080/categories/{{categoryId}}}}
Authorization: {{Authorization}}
Content-Type: application/json

{
  "topic": "수정된카테고리"
}


### 카데고리 삭제
DELETE http://localhost:8080/categories/{{categoryId}}
Authorization: {{Authorization}}



### 게시글 등록
POST http://localhost:8080/posts
Authorization: {{Authorization}}
Content-Type: application/json

{
  "title": "게시글 제목",
  "content": "게시글 내용",
  "categoryTopic": "{{categoryTopic}}"
}


### 게시글 단일 조회
GET http://localhost:8080/posts/{{postId}}
Authorization: {{Authorization}}


### 전체 카테고리의 게시글 조회
GET http://localhost:8080/posts


### 카테고리의 게시글 조회
GET http://localhost:8080/posts?category=1


### 게시글 수정
PUT http://localhost:8080/posts/{{postId}}
Authorization: {{Authorization}}
Content-Type: application/json

{
  "title": "수정된 게시글 제목",
  "content": "수정된 게시글 내용",
  "categoryTopic": "{{categoryTopic}}"
}


### 게시글 삭제
DELETE http://localhost:8080/posts/{{postId}}
Authorization: {{Authorization}}


### 댓글 작성
POST http://localhost:8080/comments
Authorization: {{Authorization}}
Content-Type: application/json

{
  "postId": {{postId}},
  "content": "댓글 내용"
}


### 댓글 수정
PUT http://localhost:8080/comments/{{postId}}
Authorization: {{Authorization}}
Content-Type: application/json

{
  "postId": {{postId}},
  "content": "수정된 댓글내용"
}

### 댓글 삭제
DELETE http://localhost:8080/comments/{{postId}}
Authorization: {{Authorization}}


### 좋아요 기능
POST http://localhost:8080/likes?contentType=post&contentId=3
Authorization:{{Authorization}}


### 스크랩 기능
POST http://localhost:8080/scraps/posts/2
Authorization:{{Authorization}}


### 스크랩 내용 확인
GET http://localhost:8080/scraps/users/{{userId}}
Authorization: {{Authorization}}