

@post_id = 1
@comment_id = 1
@title = 제목
@content = 내용테스트

@categoryid = 1
@categoryTopic = Web
@username = testuser99
@password = Password123!
@nickname = 닉네임1
@email = test9@example.com


# 일반권한인 유저 테스트입니다.

### 유저 회원 가입
POST http://localhost:8080/auth/sign-up
Content-Type: application/json

{
  "username":"{{username}}",
  "password":"{{password}}",
  "nickname":"{{nickname}}",
  "email":"{{email}}"
}
### 1. 로그인 (Login)
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "{{username}}",
  "password": "{{password}}"
}

> {%
    client.global.set("Authorization", response.headers.valueOf("Authorization"));
    client.global.set("X-Refresh-Token", response.headers.valueOf("X-Refresh-Token"));
%}

###  게시글 작성
POST http://localhost:8080/posts
Authorization: {{Authorization}}
Content-Type: application/json

{
  "title": "{{title}}",
  "content": "{{content}}",
  "categoryTopic": "{{categoryTopic}}"

}

###  단일 게시글 조회
GET http://localhost:8080/posts/{{post_id}}
Content-Type: application/json

###  전체 게시글 조회
GET http://localhost:8080/posts
Content-Type: application/json

###  카테고리 별 게시글 조회
GET http://localhost:8080/posts?category={{categoryid}}
Content-Type: application/json

### 게시글 수정
PUT http://localhost:8080/posts/{{post_id}}
Authorization: {{Authorization}}
Content-Type: application/json

{
  "title": "제목수정하기",
  "content": "내용수정하기",
  "categoryTopic": "Mobile"
}

### 게시글 삭제
DELETE http://localhost:8080/posts/{{post_id}}
Authorization: {{Authorization}}
